name: Publish to nuget
on:
  push:
    branches: 
      - master
jobs:
  publish:
    name: Build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - uses: aarnott/nbgv@master
        id: nbgv
        with:
          path: src/DutchAndBold.MoneybirdSdk
        
      - name: Publish MoneybirdSdk
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: src/DutchAndBold.MoneybirdSdk/DutchAndBold.MoneybirdSdk.csproj
          VERSION_STATIC: ${{ steps.nbgv.outputs.NuGetPackageVersion }}
          TAG_COMMIT: false
          NUGET_KEY: ${{secrets.API_KEY_NUGET}}
          INCLUDE_SYMBOLS: true
